apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
  - target:
      kind: Application
      name: podinfo-workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: podinfo-workload-preprod-westus2
      - op: replace
        path: /spec/destination/server
        value: "https://preprod-westus2.vcluster-preprod-westus2:443"
