apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: podinfo-workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: podinfo-workload-dev-eastus
      - op: replace
        path: /spec/destination/server
        value: "https://dev-eastus.vcluster-dev-eastus:443"
