apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: podinfo-workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: podinfo-workload-dev-southcentralus
      - op: replace
        path: /spec/destination/server
        value: "https://dev-southcentralus.vcluster-dev-southcentralus:443"
  - target:
      group: monitoring.coreos.com
      version: v1
      kind: ServiceMonitor
      name: podinfo-workload
    patch: |-
      - op: replace
        path: /metadata/name
        value: podinfo-workload-dev-southcentralus
      - op: replace
        path: /spec/selector/matchLabels/name
        value: podinfo-workload-dev-southcentralus
